spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:./data/demo
    driver-class-name: org.h2.Driver
    username: sa
    password: pwd1
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
    password: pwd1
    schemas: app-db
    url: jdbc:h2:file:./data/demo
    user: sa
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
