spring:
  datasource:
    password: pwd1
    url: jdbc:h2:mem:DATABASE
    username: admin
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: filesystem:db/migration
    password: pwd1
    schemas: app-db
    url: jdbc:h2:mem:DATABASE
    user: admin
